image:
  file: .gitpod.dockerfile

tasks:
  - name: setup
    init: |
      yarn
      cp .env.example .env
      yarn l10n:generate
    command: yarn start

ports:
  - port: 4200
    onOpen: open-browser
