name: CI

on:
  push:
    branches: [ development, master ]
  pull_request:
    branches: [ development, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn
    - run: yarn l10n:generate
    - run: yarn lint
    - run: COVERAGE=true yarn test
    - run: ROOT_URL=open-event-frontend ember build -prod
    - name: Code Coverage
      uses: codecov/codecov-action@v1
